@hostname = localhost:3000
###
//AUTH MODULE
###
//sign in
# @name login
POST /auth/login  HTTP/1.1
Host: {{hostname}}
content-type: application/json

{
    "username": "test",
    "password": "123"
}
###
@authToken = {{login.response.body.access_token}}
###
//get signed user
GET /auth/me HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//USER MODULE
###
//list users
GET /users HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//create user
POST /users HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"name": "test",
	"password": "123"
	
}
