###
@hostname = localhost:3000
###
//AUTH MODULE
###
//sign up
POST /auth/signup  HTTP/1.1
Host: {{hostname}}
content-type: application/json

{
    "name": "test",
    "password": "test"
}

###
//sign in
# @name signin
POST /auth/signin  HTTP/1.1
Host: {{hostname}}
content-type: application/json

{
    "username": "test",
    "password": "test"
}
###
@authToken = {{signin.response.body.access_token}}
###
//get signed user
GET /auth/me HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//USER MODULE
###
@userId=a7a97e52-609f-4705-8ff6-b53bdb02d85a
###
//list users
GET /users HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//get user
GET /users/{{userId}} HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//remove user
DELETE /users/{{userId}} HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//create user
POST /users HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"name": "test",
	"password": "123"
	
}
###
//NATIONALITY MODULE
###
@nationalityId=056674fa-62d4-4fe9-ba06-cc1a665a08b1
###
//list nationalities
GET /nationalities HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//get nationality
GET /nationalities/{{nationalityId}} HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//remove nationality
DELETE /nationalities/{{nationalityId}} HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
###
//create nationality
POST /nationalities HTTP/1.1
Host: localhost:3000
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
	"name": "Polish"
}
###