version: "3.7"
services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    env_file:
      - docker.env
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    logging:
      driver: none
    ports:
      - 8080:80
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
